// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lidoimkpqlclzluzmfwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZG9pbWtwcWxjbHpsdXptZndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMTY5NTcsImV4cCI6MjA3MDc5Mjk1N30.fp8n_ySdcavToD4yD1mr72e1OFiUkvdkaQYNXOze_dA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});